<?php

function cu_faculty_publication_bundle_block_info() {
  $blocks['publications_by_faculty'] = array(
    'info' => t('Publications by Faculty Member'),
  );
  return $blocks;
}

function cu_faculty_publication_bundle_block_view($delta = '') {
  $block = array();
  if ($delta =='publications_by_faculty') {

    $block['subject'] = 'Example Faculty Publication Block';
    //$block['content']['publications']['#markup'] = 'content goes here.';
    $node = menu_get_object();
    dpm($node);
    $id = $node->field_fis_id[LANGUAGE_NONE][0]['value'];
    // $json = file_get_contents(drupal_get_path('module', 'cu_faculty_publication_bundle') . '/data/example.json');
    $es_data = curl_init();
    curl_setopt($es_data, CURLOPT_URL, 'https://experts.colorado.edu/es/webex-rc1/_search?q=authors.uri:experts.colorado.edu/display/fisid_'.$id);
    curl_setopt($es_data, CURLOPT_RETURNTRANSFER,true);
    curl_setopt($es_data, CURLOPT_HEADER, false); 
    
    $json = curl_exec($es_data);
    curl_close($es_data);
    $publications = json_decode($json);

    foreach ($publications->hits->hits as $listing) {
      $contents = (array) $listing->_source;
      $block['content']['publications'][]['#markup'] = theme('faculty_publication_name', $contents);
    }

  }
  return $block;
}

function cu_faculty_publication_bundle_theme(&$existing, $type, $theme, $path) {
  $registry = array();
  $template_dir = drupal_get_path('module', 'cu_faculty_publication_bundle') . '/templates';
  $registry['faculty_publication_author'] = array(
    'template' => 'faculty-publication-author',
    'path' => $template_dir,
    'render element' => 'elements',
  );
  $registry['faculty_publication_name'] = array(
    'template' => 'faculty-publication-name',
    'path' => $template_dir,
    'render element' => 'elements',
  );

  return $registry;
}
