<?php
/**
 * Implements hook_block_info().
 */
function cu_faculty_publication_bundle_block_info() {
  $blocks['publications_by_faculty'] = array(
    'info' => t('Publications by Faculty Member'),
  );
  return $blocks;
}

/**
 * Implements hook_view().
 */
function cu_faculty_publication_bundle_block_view($delta = '') {
  // Load current person node
  $node = menu_get_object();

  // Set id and template variables
  $fis_id = $node->field_fis_id[LANGUAGE_NONE][0]['value'];
  $publications_template = $node->field_display_publications_by[LANGUAGE_NONE][0]['value'];
  
  // Both fis id AND publications display type must be set to build block
  if ($fis_id && $publications_template){
    // Initialize block 
    $block = array();
    if ($delta =='publications_by_faculty') {
      //Load custom block title
      $block_heading = $node->field_publications_heading[LANGUAGE_NONE][0]['safe_value'];
      if ($block_heading) {
        $block['subject'] = $block_heading;
      }

      //$block['content']['publications']['#markup'] = 'content goes here.';
      
      // Get number of publications we want to display in block from person node
      $publications_size = $node->field_number_of_publications[LANGUAGE_NONE][0]['value'];

      // Initialize curl
      $es_data = curl_init();

      // Build query
      curl_setopt($es_data, CURLOPT_URL, 'https://experts.colorado.edu/es/webex-rc1/_search?q=authors.uri:experts.colorado.edu/display/fisid_'.$fis_id.'&size='.$publications_size);
      curl_setopt($es_data, CURLOPT_RETURNTRANSFER,true);
      curl_setopt($es_data, CURLOPT_HEADER, false); 
      
      // Send request to elastic search api
      $json = curl_exec($es_data);
      curl_close($es_data);

      // Turn response into json format
      $publications = json_decode($json);

      // Loop through json response and display publication in template
      foreach ($publications->hits->hits as $listing) {
        $contents = (array) $listing->_source;
        $block['content']['publications'][]['#markup'] = theme($publications_template, $contents);
      }

    }
    return $block;
  }
}

/**
 * Implements hook_theme().
 */
function cu_faculty_publication_bundle_theme(&$existing, $type, $theme, $path) {
  $registry = array();
  $template_dir = drupal_get_path('module', 'cu_faculty_publication_bundle') . '/templates';
  $registry['faculty_publication_author'] = array(
    'template' => 'faculty-publication-author',
    'path' => $template_dir,
    'render element' => 'elements',
  );
  $registry['faculty_publication_name'] = array(
    'template' => 'faculty-publication-name',
    'path' => $template_dir,
    'render element' => 'elements',
  );

  return $registry;
}
